version: "1.0"

services:
  app:
    container_name: "app"
    build: ./app
    env_file:
      - .env
    ports:
      - 8080:8000
    volumes:
      - ./app:/app
    depends_on:
      - rabbitmq
      - database

  web-proxy:
    container_name: "web-proxy"
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app

  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:4.1-rc-management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: on-failure

  database:
    container_name: "postgres"
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  rabbitmq_data:
  postgres_data: